### ISSUE TITLE
unique_id support for Home Assistant

### ISSUE THREAD

**Issue by dobrynski** [fbradyirl/openwebifpy#11]
* openwebifpy version: current
* Python version: current
* Operating System: any

### Description

This is a feature request for the Home Assistant interface as I have no idea where else to file it

### What I Did

Home Assistant supports unique_id which allows for renaming of the entity and friendly name via the web UI. The enigma2 component does not support this.. However it seems like it would be simple to add this functionality. Even though I developed an Enigma2 custom_component I'm below average at best at this sort of thing but I was able to quickly knock up this example of how a unique_id could be generated:
```python
import openwebif.api
client = openwebif.api.CreateDevice(‘beyonwizt4.local')
unique_id = client.mac_address.replace(':', '')
print(unique_id)
```
It would be fantastic if this could be added to the home assistant enigma2 component.. 

Thank you in advance.
Regards,
Michal

**Comment by fbradyirl** [comment]
Complete in PR above.
