### ISSUE TITLE
Add Notification option

### ISSUE THREAD

**Issue by autinerd** [fbradyirl/openwebifpy#12]
It would be cool to add the possibility to send notifications via HomeAssistant to the TV.
I could implement it, if the package is still maintained at all.

**Comment by SlavikS-PL** [comment]
@autinerd it would be great if you will implement such feature in core integration. I used #https://github.com/cinzas/homeassistant-enigma-player custom component but it has been stopped working some time ago.

**Comment by fbradyirl** [comment]
@autinerd if you want to open a PR we can get your branch merged here.

**Comment by autinerd** [comment]
The PR is #13 :)

**Comment by fbradyirl** [comment]
Merged and released in v3.2.0
