### ISSUE TITLE
No picon url defaults back to getting screen grab

### ISSUE THREAD

**Issue by leaskovski** [fbradyirl/openwebifpy#14]
* openwebifpy version: 3.1.1
* Python version: 3.7
* Operating System: Raspbian Buster (Home Assistant venv)

When using the engima2 integration in Home Assistant, which uses the 3.1.1 version of this component, when configuring to use a picon image for the channel, this means that a picon url is built and a picon image is tried to be retrieved.  If, for some reason the picon url cannot be retrieved, the component falls back to getting a screen grab.  This maybe ok for some boxes, but for my enigma2 box, it causes a 1 seconds freeze/slow down.

It would be preferable if this fall back was configurable to not grab a screen grab.

**Comment by fbradyirl** [comment]
Fixed in commit.

https://github.com/fbradyirl/openwebifpy/commit/1f303b4a1878e406f87b260744c7991ca8433db8
