### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by autinerd** [fbradyirl/openwebifpy#17]
Hi,

I just wanted to ask if the project is still active/maintained. I am just modernizing the homeassistant integration and there I spotted bugs and in the midterm the need to restructure the library (async, more endpoints etc.) but the last commit was 3 years ago. My question is if it makes sense to create a pull request here to incorporate the changes.

When you don't want to maintain the project any longer @fbradyirl, I would have no problem with taking it over.

Greetings,
Sid

**Comment by fbradyirl** [comment]
Hi Sid,

Yes that would be no problem. I would be happy if you're willing to take it over. Should I make you an admin on the repo or do you want to start your own fresh?

Finbarr

**Comment by autinerd** [comment]
I created a fork and will work on that. The only thing would be adding me on PyPI, so that I can create new releases.

**Comment by fbradyirl** [comment]
Could you provide a link to your fork for reference here?

**Comment by autinerd** [comment]
Of course, it is https://github.com/autinerd/openwebifpy

**Comment by fbradyirl** [comment]
Thanks. It's great to add features and modernise the library. When I started this, I had no kids and more spare time but this has all changed 😂

**Comment by autinerd** [comment]
Haha yeah, I know how it is to have no spare time :sweat_smile: And there are of course things which are more important :blush:
